# Installation of MSYS2 ang GCC toolchain to compile a C project on Windows
# Snippet copied from https://docs.travis-ci.com/user/reference/windows/
before_install:
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        ## Installing GCC
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-gdb mingw64/mingw-w64-x86_64-make
        ## End of GCC installation
        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make  # so that Autotools can find it
        ;;
    esac

before_cache:
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
  directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64
# End of MSYS2 configuration

# Matrix
language: c
compiler:
  - clang
  - gcc
os:
  - osx
  - linux
  - windows
env:
  - BUILD_TYPE=Release     # Optimised for speed
  - BUILD_TYPE=MinSizeRel  # Optimised for size
jobs:
  exclude:
    - os: windows
      compiler: clang

# Configure out-of-source build with cmake
before_script:
  - which gcc
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

# Compile all targets
script:
  - cmake --build . --parallel 8 --clean-first

# Run tests
after_success:
  - ls -l
  - ./testascon
  - ./testasconshared
