# Github actions script to build the project develop branch
name: Build Develop

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:
    branches:
      - develop

jobs:
  build_and_test_unixlike:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        build_type:
          - Release
          - MinSizeRel
        compiler:
          - gcc
          - clang
    steps:
      - uses: actions/checkout@v2
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_C_COMPILER=${{matrix.compiler}}
      - name: Build all targets
        run: cmake --build ${{github.workspace}}/build --parallel 8 --clean-first
      - name: Test with Atto
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure

  # Separate job for Windows, as it requires the MSYS installation beforehand.
  # Inspired by from https://ariya.io/2020/07/on-github-actions-with-msys2
  build_and_test_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type:
          - Release
          - MinSizeRel
        compiler:
          - gcc
          - clang
        msystem:
          - MINGW64
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: mingw-w64-x86_64-cmake make
      - name: Install GCC
        if: matrix.compiler == 'gcc'
        run: pacman --noconfirm -S mingw-w64-x86_64-gcc
      - name: install Clang
        if: matrix.compiler == 'clang'
        run: pacman --noconfirm -S mingw-w64-x86_64-clang
      - name: Check the compiler version
        run: |
          cmake --version
          ${{ matrix.compiler }} --version
      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_C_COMPILER=${{matrix.compiler}} -G "MSYS Makefiles";
      - name: Build all targets
        run: cmake --build build --parallel 8 --clean-first
      - name: Test with Atto
        working-directory: build
        run: ctest --output-on-failure
