# Github actions script to build the project develop branch
name: Build Develop

on:
  push:
    branches:
      - develop
      - release/*
      - feature/*
  pull_request:
    branches:
      - develop

jobs:
  build_and_test_unixlike:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false  # True to stop on the first job failing
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
          - macos-10.15
          - macos-11.0
        build_type:
          - Debug
          - Release
          - MinSizeRel
        compiler:
          - gcc
          - clang
    steps:
      - uses: actions/checkout@v2
      - name: Check the compiler version
        run: |
          cmake --version
          ${{ matrix.compiler }} --version
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_C_COMPILER=${{matrix.compiler}}
      - name: Build all targets
        run: cmake --build ${{github.workspace}}/build --parallel 8 --clean-first
      - name: Test with Atto
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure

  build_and_test_windows:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false  # True to stop on the first job failing
      matrix:
        os:
          - windows-2019
          - windows-2016
        build_type:
          - Debug
          - Release
          - MinSizeRel
        # No compiler settings: defaults to MSVC
    steps:
      - uses: actions/checkout@v2
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
      - name: Build all targets
        run: cmake --build ${{github.workspace}}/build --parallel 8 --clean-first
      - name: Test with Atto
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure
